import { Footer } from "@/components/user/footer";
import { Header } from "@/components/user/header";
import type { Metadata } from "next";
import { getCategories, getProductsSearchList } from "./action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categoriesResponse = await getCategories();
  const productsSearchListResponse = await getProductsSearchList();
  return (
    <>
      <Header
        categories={categoriesResponse}
        products={productsSearchListResponse}
      />
      {children}
      <Footer />
    </>
  );
}
